insert into tbl_nhacc(nameSupplier, address, email, mobile,status) values('NXB Kim đồng', '55 Quang Trung, Hà Nội, Việt Nam', 'info@nxbkimdong.com.vn', '02439434490', true);
insert into tbl_nhacc(nameSupplier, address, email, mobile,status) values('NXB Trẻ', '161B Lý Chính Thắng, Phường 7, Quận 3, Thành phố Hồ Chí Minh.', 'hopthubandoc@nxbtre.com.vn','02839317849', true);
insert into tbl_nhacc(nameSupplier, address, email, mobile,status) values('Nhã Nam', '59 Đỗ Quang, KĐT Trung Hòa Nhân Chính, Cầu Giấy, Hà Nội', 'bookstore@nhanam.vn', '090456789', true);
insert into tbl_nhacc(nameSupplier, address, email, mobile,status) values('Thái Hà', 'Lô B2 – khu Đấu giá 3ha, Tổ dân phố số 1, Phúc Diễn, Bắc Từ Liêm, Hà Nội.', '', '02437930480', true);
insert into tbl_nhacc(nameSupplier, address, email, mobile,status) values('Phương Nam', 'Lầu 1, số 940 Đường 3/2, P.15, Q.11, TP. Hồ Chí Minh.', 'ttps://www.facebook.com/nhasachphuongnam/', '9006656', true);
insert into tbl_nhacc(nameSupplier, address, email, mobile,status) values('Đông A', '113 Đông Các, Ô Chợ Dừa, Đống Đa, Hà Nội', ' ', '38569381', true);
insert into tbl_nhacc(nameSupplier, address, email, mobile,status) values('NXB Hồng Đức', 'Quận Hà Đông, Hà Nội', 'hongduchue@gmail.com', '0906566767', true);
insert into tbl_nhacc(nameSupplier, address, email, mobile,status) values('NXB Lao động', '175 Giảng Võ, Q. Đống Đa, Hà Nội', '', '0438515380', true);

Insert into tbl_khachhang(created,address,mobile,email,name,password, status,user_status ) values('2021-1-1',
'Bắc Ninh', 0975968806, 'hieu@gmail.com', 'Nguyễn Đình Hiếu','hieu123', 0, 1);
Insert into tbl_nhanvien(address,mobile,email,name,position, status,username, password,status_login ) values('Bắc Ninh', '0975968806',
'hieu@gmail.com','Nguyễn Đình Hiếu',1,0,'hieu@gmail.com', 'hieu123', 1);

insert into tbl_danhmuc(id, name, describes, status) values(1, 'Sách kỹ năng', '', 1);
insert into tbl_danhmuc(id, name, describes, status) values(2, 'Sách thiếu nhi', 'Cho trẻ em từ 0 đến 12 tuổi', 1);
insert into tbl_danhmuc(id, name, describes, status) values(3, 'Sách tâm lý', '', 1);
insert into tbl_danhmuc(id, name, describes, status) values(4, 'Sách light novel', '', 1);
insert into tbl_danhmuc(id, name, describes, status) values(5, 'Sách tiểu thuyết', '', 1);

insert into tbl_sanpham(id,nameProduct,imgProduct, describes, status, quantity, discount, percentDiscount, price, view, idDM,idNCC,author)
values(1,'Dế Mèn Phiêu Lưu Ký (Tái Bản 2019)','336cb89bfe1dfefcaea03be376cea7d8.jpg','<p>Ấn bản minh họa màu đặc biệt
 của Dế Mèn phiêu lưu ký, với phần tranh ruột được in hai màu xanh - đen ấn tượng, gợi không khí đồng thoại.</p>
<p>“Một con dế đã từ tay ông thả ra chu du thế giới tìm những điều tốt đẹp cho loài người. Và con dế ấy đã mang 
tên tuổi ông đi cùng trên những chặng đường phiêu lưu đến với cộng đồng những con vật trong văn học thế giới, đến
 với những xứ sở thiên nhiên và văn hóa của các quốc gia khác. Dế Mèn Tô Hoài đã lại sinh ra Tô Hoài Dế Mèn, một
 nhà văn trẻ mãi không già trong văn chươ” - Nhà phê bình Phạm Xuân Nguyên</p>
<p>“Ông rất hiểu tư duy trẻ thơ, kể với chúng theo cách nghĩ của chúng, lí giải sự vật theo lô gích của trẻ. Hơn thế,
 với biệt tài miêu tả loài vật, Tô Hoài dựng lên một thế giới gần gũi với trẻ thơ. Khi cần, ông biết đem vào chất du 
 ký khiến cho độc giả nhỏ tuổi vừa hồi hộp theo dõi, vừa thích thú khám phá.” - TS Nguyễn Đăng Điệp</p><p>Giá sản
 phẩm trên Tiki đã bao gồm thuế theo luật hiện hành. Tuy nhiên tuỳ vào từng loại sản phẩm hoặc phương thức, địa chỉ 
 giao hàng mà có thể phát sinh thêm chi phí khác như phí vận chuyển, phụ phí hàng cồng kềnh, ...</p>',
1, 20,28000,44, 50000, 0,2,1,'Tô Hoài');

insert into tbl_sanpham(id,nameProduct,imgProduct, describes, status, quantity, discount, percentDiscount, price, view, idDM,idNCC,author)
values(2,'Những Truyện Hay Viết Cho Thiếu Nhi - Tô Hoài (Tái Bản 2019)','26aeb8f6aa491d6331f5d6c18044d27b.jpg',
'<p>Tập truyện tuyển chọn những truyện hay viết cho thiếu nhi của nh&agrave; văn T&ocirc; Ho&agrave;i: Đ&aacute;m cưới chuột, V&otilde; sĩ Bọ Ngựa, D&ecirc; v&agrave; Lợn, Hai con ngỗng, B&agrave;n Qu&yacute; v&agrave; Ngựa Con, M&ugrave;a xu&acirc;n đ&atilde; về đấy&hellip;</p>
 <p>&ldquo;Bạn đọc nhỏ tuổi hay người lớn đọc đồng thoại? Những t&aacute;c phẩm viết cho lứa tuổi thơ nổi tiếng trong nước v&agrave; thế giới đ&atilde; trả lời c&acirc;u hỏi ấy. Một s&aacute;ng t&aacute;c hay cho c&aacute;c em cũng l&agrave;m cho cả người lớn thấy hay. C&aacute;c em v&agrave; người lớn đều thu nhận được ở t&aacute;c phẩm ấy những th&ocirc;ng cảm cho mỗi lứa tuổi kh&aacute;c nhau, m&agrave; người lớn kh&ocirc;ng cần phải giả l&agrave;m trẻ em mới hiểu được. Người lớn vốn đ&atilde; th&iacute;ch th&uacute; đọc rất h&agrave;o hứng những t&aacute;c phẩm tưởng tượng c&ograve;n &ldquo;hoang đường&rdquo; hơn truyện đồng thoại kia m&agrave;.&rdquo; - Nh&agrave; văn T&ocirc; Ho&agrave;i</p>
 <p>Gi&aacute; sản phẩm tr&ecirc;n Tiki đ&atilde; bao gồm thuế theo luật hiện h&agrave;nh. Tuy nhi&ecirc;n tuỳ v&agrave;o từng loại sản phẩm hoặc phương thức, địa chỉ giao h&agrave;ng m&agrave; c&oacute; thể ph&aacute;t sinh th&ecirc;m chi ph&iacute; kh&aacute;c như ph&iacute; vận chuyển, phụ ph&iacute; h&agrave;ng cồng kềnh, ...</p>',
 1,40,54900,0,54900,0,2,1,'Tô Hoài');
insert into tbl_sanpham(id,nameProduct,imgProduct, describes, status, quantity, discount, percentDiscount, price, view, idDM,idNCC,author)
values(3,'Nguồn Gốc Các Loài','86f8da4e75cda71360f151461af491b1.jpg',
'<p><strong>Nguồn Gốc C&aacute;c Lo&agrave;i</strong><br />
 &ldquo;Nguồn gốc c&aacute;c lo&agrave;i&rdquo; &ndash; T&aacute;c phẩm của Charles Darwin do Sabina Radeva thuật lại v&agrave; minh họa.<br />
 &ldquo;Một dự &aacute;n cực k&igrave; quan trọng, được thực hiện theo c&aacute;ch đẹp đẽ nhất&rdquo; (Emma Darwin)<br />
 Từ biến chủng lạ l&ugrave;ng đến đấu tranh sinh tồn, từ vi khuẩn nhỏ nhất đến C&acirc;y Sự Sống vĩ đại: trong phi&ecirc;n bản chuyển thể tuyệt đẹp từ t&aacute;c phẩm trứ danh của Darwin n&agrave;y, bạn sẽ kh&aacute;m ph&aacute; một học thuyết mang t&iacute;nh đột ph&aacute;, đ&atilde; biến đổi thế giới m&atilde;i m&atilde;i: THUYẾT TIẾN H&Oacute;A<br />
 Một t&aacute;c phẩm nghệ thuật sinh động, đẹp đẽ, v&agrave; cực k&igrave; quan trọng với tất cả ch&uacute;ng ta khi bắt đầu t&igrave;m hiểu thế giới chung quanh.</p>
 <p>Gi&aacute; sản phẩm tr&ecirc;n Tiki đ&atilde; bao gồm thuế theo luật hiện h&agrave;nh. Tuy nhi&ecirc;n tuỳ v&agrave;o từng loại sản phẩm hoặc phương thức, địa chỉ giao h&agrave;ng m&agrave; c&oacute; thể ph&aacute;t sinh th&ecirc;m chi ph&iacute; kh&aacute;c như ph&iacute; vận chuyển, phụ ph&iacute; h&agrave;ng cồng kềnh, ...</p>
 ', 1,40,90900,0,90900,0,2,1,'');
insert into tbl_sanpham(id,nameProduct,imgProduct, describes, status, quantity, discount, percentDiscount, price, view, idDM,idNCC,author)
values(4,'Doraemon - Truyện dài - Tập 23: Nobita Và Những Pháp Sư Gió Bí Ẩn (Tái Bản 2019)','388acf0479a253f1a0cd0d304600d745.jpg',
'<p>Những c&acirc;u chuyện về ch&uacute; m&egrave;o m&aacute;y th&ocirc;ng minh Doraemon v&agrave; nh&oacute;m bạn Nobita, Shizuka, Suneo, Jaian, Dekisugi sẽ đưa ch&uacute;ng ta bước v&agrave;o thế giới hồn nhi&ecirc;n, trong s&aacute;ng đầy ắp tiếng cười với một kho bảo bối k&igrave; diệu - những bảo bối biến ước mơ của ch&uacute;ng ta th&agrave;nh sự thật. Nhưng tr&ecirc;n tất cả Doraemon l&agrave; hiện th&acirc;n của t&igrave;nh bạn cao đẹp, của niềm kh&aacute;t khao vươn tới những tầm cao.</p>
 <p>Gi&aacute; sản phẩm tr&ecirc;n Tiki đ&atilde; bao gồm thuế theo luật hiện h&agrave;nh. Tuy nhi&ecirc;n tuỳ v&agrave;o từng loại sản phẩm hoặc phương thức, địa chỉ giao h&agrave;ng m&agrave; c&oacute; thể ph&aacute;t sinh th&ecirc;m chi ph&iacute; kh&aacute;c như ph&iacute; vận chuyển, phụ ph&iacute; h&agrave;ng cồng kềnh, ...</p>
', 1,50,18000,0,18000,0,2,1,'Fujiko F Fujio');

insert into tbl_sanpham(id,nameProduct,imgProduct, describes, status, quantity, discount, percentDiscount, price, view, idDM,idNCC,author)
values(5,'Combo Shin Cậu bé bút chì  Truyện Ngắn 50 tập ( Tái Bản 2019 )','cc010f27ae2201b76f10061fc3677374.jpg',
'<p>Được ph&aacute;t h&agrave;nh lần đầu v&agrave;o năm 1992, bộ truyện sớm g&acirc;y được tiếng vang đối với độc giả Nhật Bản v&agrave; nhiều nước kh&aacute;c tr&ecirc;n thế giới. V&agrave;i năm sau đ&oacute;, loạt phim hoạt h&igrave;nh về cậu b&eacute; Shin cũng được sản xuất v&agrave; ph&aacute;t s&oacute;ng li&ecirc;n tục cho đến b&acirc;y giờ.<br />
 Về h&igrave;nh thức thể hiện, t&aacute;c giả sử dụng b&uacute;t ph&aacute;p đơn giản, thậm ch&iacute; c&oacute; vẻ ng&acirc;y ng&ocirc; hơn so với c&aacute;c bộ manga kh&aacute;c. Nội dung truyện cũng đơn giản: tất cả xoay quanh nh&acirc;n vật ch&iacute;nh l&agrave; cậu b&eacute; Shin 5 tuổi với những mối quan hệ th&acirc;n sơ, bố mẹ, h&agrave;ng x&oacute;m, thầy c&ocirc;, bạn b&egrave;, người quen v&agrave; cả những người kh&ocirc;ng quen.<br />
 Mỗi tập truyện khoảng 120 trang, nhưng cứ thử cầm l&ecirc;n xem, bạn sẽ kh&ocirc;ng thể rời mắt khỏi cuốn s&aacute;ch cho đến tận trang cuối c&ugrave;ng. Với t&agrave;i năng kể chuyện hấp dẫn, t&aacute;c giả đ&atilde; biến c&aacute;c trang s&aacute;ch của m&igrave;nh th&agrave;nh những s&acirc;n chơi ngập tr&agrave;n tiếng cười của những c&ocirc; b&eacute;, cậu b&eacute; hồn nhi&ecirc;n v&agrave; một thế giới tuổi thơ đa sắc m&agrave;u.<br />
 Những b&agrave;i học gi&aacute;o dục nhẹ nh&agrave;ng, thấm th&iacute;a cũng được lồng gh&eacute;p một c&aacute;ch kh&eacute;o l&eacute;o trong từng t&igrave;nh huống truyện. C&oacute; thể Shin l&agrave; một cậu b&eacute; c&aacute; t&iacute;nh, hiếu động. C&oacute; thể những tr&ograve; tinh nghịch của Shin đ&ocirc;i khi qu&aacute; trớn, chẳng chừa một ai. Nhưng sau những sự cố do Shin g&acirc;y ra, người lớn thấy m&igrave;nh cần quan t&acirc;m đến trẻ con nhiều hơn nữa, c&aacute;c bạn đọc nhỏ tuổi chắc hẳn cũng được dịp nh&igrave;n nhận lại bản th&acirc;n, để ph&acirc;n biệt điều tốt điều xấu trong cuộc sống.</p>
 <p>Gi&aacute; sản phẩm tr&ecirc;n Tiki đ&atilde; bao gồm thuế theo luật hiện h&agrave;nh. Tuy nhi&ecirc;n tuỳ v&agrave;o từng loại sản phẩm hoặc phương thức, địa chỉ giao h&agrave;ng m&agrave; c&oacute; thể ph&aacute;t sinh th&ecirc;m chi ph&iacute; kh&aacute;c như ph&iacute; vận chuyển, phụ ph&iacute; h&agrave;ng cồng kềnh, ...</p>
 ',1,10,855000,10,950000, 0,2,1,'Usui Yoshito');
insert into tbl_sanpham(id,nameProduct,imgProduct, describes, status, quantity, discount, percentDiscount, price, view, idDM,idNCC,author)
values(7,'Your Name','dc00eccce4b4e0ec7098ff41df67c686.jpg','<p dir="ltr">Mitsuha là nữ sinh trung học s&ocirc;́ng ở vùng qu&ecirc; hẻo lánh. M&ocirc;̣t ngày nọ, c&ocirc; mơ th&acirc;́y mình ở Tokyo trong một căn ph&ograve;ng xa lạ, biến thành con trai, gặp những người bạn chưa từng quen bi&ecirc;́t.</p>
 <p dir="ltr">Trong khi đ&oacute; ở m&ocirc;̣t nơi khác, Taki, một nam sinh trung học người Tokyo lại mơ th&acirc;́y mình biến thành con gái, s&ocirc;́ng ở vùng qu&ecirc; hẻo lánh.</p>
 <p dir="ltr">Cu&ocirc;́i cùng hai người họ nh&acirc;̣n ra đang bị hoán đ&ocirc;̉i với nhau qua gi&acirc;́c mơ. K&ecirc;̉ từ lúc hai con người xa lạ ấy gặp nhau, bánh xe s&ocirc;́ ph&acirc;̣n bắt đ&acirc;̀u chuy&ecirc;̉n đ&ocirc;̣ng.</p>
 <p dir="ltr">Đ&acirc;y là phi&ecirc;n bản ti&ecirc;̉u thuy&ecirc;́t của b&ocirc;̣ phim hoạt hình Your Name, do ch&iacute;nh đạo diễn Shinkai Makoto chấp bút.</p>
 ',1,25,56250,25,75000,0,2,1,'Shinkai Makoto');
insert into tbl_sanpham(id,nameProduct,imgProduct, describes, status, quantity, discount, percentDiscount, price, view, idDM,idNCC,author)
values(8, 'Về Chuyện Tôi Chuyển Sinh Thành Slime Tập 1','ee89c67084f8fefd5aa817f3e9b11635.jpg','<p>Th&ocirc;ng tin qu&agrave; tặng k&egrave;m:</p>
 <ul>
 	<li>Bản đặc biệt tặng k&egrave;m boolmark, poster khổ lớn, bảng sticker</li>
 	<li>Bản thường tặng k&egrave;m bookmark, postẻ khổ lớn</li>
 </ul>
 <p>*Review &ldquo;Về chuyện t&ocirc;i chuyển sinh th&agrave;nh Slime&rdquo; &ndash; Fuse</p>
 <p>Mikami Satoru &ndash; một nh&acirc;n vi&ecirc;n văn ph&ograve;ng b&igrave;nh thường - đ&atilde; ba mươi bảy c&aacute;i xu&acirc;n xanh nhưng vẫn c&ograve;n l&agrave; một thanh ni&ecirc;n trai t&acirc;n ch&iacute;nh hiệu. Một ng&agrave;y nọ, v&igrave; bảo vệ đồng nghiệp của m&igrave;nh, anh bị một t&ecirc;n đi&ecirc;n cầm dao đ&acirc;m tr&ecirc;n phố. Trong những gi&acirc;y ph&uacute;t cuối đời, khi phải l&ecirc;n đường sang thế giới b&ecirc;n kia trong t&igrave;nh trạng &ldquo;h&agrave;ng c&ograve;n nguy&ecirc;n tem&rdquo; v&agrave; trong đầu anh kh&ocirc;ng ngừng vang l&ecirc;n một giọng n&oacute;i th&ocirc;ng b&aacute;o về một loạt những năng lực kh&oacute; hiểu, anh đ&atilde; thề rằng: Nếu được t&aacute;i sinh, anh nhất định sẽ thay đổi, sẽ chủ động t&aacute;n tỉnh tất cả những người m&agrave; m&igrave;nh gặp, nhiệt t&igrave;nh theo đuổi con mồi rồi lao v&agrave;o &ldquo;ăn sạch&rdquo;&hellip;</p>
 <p>Nhưng trớ tr&ecirc;u thay khi tỉnh lại, Satoru lại kh&ocirc;ng được &ldquo;t&aacute;i sinh&rdquo; th&agrave;nh một anh ch&agrave;ng đẹp trai bảnh bao cuốn h&uacute;t như &yacute; nguyện, m&agrave; lại th&agrave;nh một thứ sinh vật &egrave;o uột trơn tuột, kh&ocirc;ng thể nh&igrave;n được, nghe được, hay n&oacute;i được.</p>
 <p>&ldquo;T&ocirc;i cũng chẳng biết bản th&acirc;n tr&ocirc;ng như thế n&agrave;o. T&ocirc;i cảm thấy cơ thể m&igrave;nh cứ&hellip; trơn tuột, giống như thạch vậy, hệt như h&igrave;nh d&aacute;ng của loại &ldquo;qu&aacute;i vật&rdquo; đ&oacute;. Thực ra t&ocirc;i cũng đ&atilde; nghĩ đến khả năng n&agrave;y từ n&atilde;y rồi.</p>
 <p>T&ocirc;i thực sự đ&atilde;&hellip; được t&aacute;i sinh th&agrave;nh một con slime&hellip;&rdquo;</p>
 <p>Dần d&agrave; chấp nhận số phận rằng bản th&acirc;n đ&atilde; bị biến th&agrave;nh một con Slime kỳ lạ, Mikami Satoru bắt đầu cuộc sống nh&agrave;n tản của m&igrave;nh tại dị giới. Tuy nhi&ecirc;n, từ khi t&igrave;nh cờ gặp được Bạo Phong Long Veldora &ndash; một con qu&aacute;i vật cấp &ldquo;thi&ecirc;n tai&rdquo; v&agrave; nhận được c&aacute;i t&ecirc;n &ldquo;Rimuru Tempest&rdquo; th&igrave; vận mệnh của anh đ&atilde; ho&agrave;n to&agrave;n thay đổi.</p>
 <p>Liệu một người được chuyển sinh v&agrave;o cơ thể của một con slime mất đi th&iacute;nh gi&aacute;c, thị gi&aacute;c sẽ l&agrave;m thế n&agrave;o để sống s&oacute;t tại dị giới đ&acirc;y? V&agrave; d&ugrave; trước khi chết đ&atilde; nhận được hai kỹ năng v&ocirc; song l&agrave; Đại Hiền Giả v&agrave; Kẻ Săn Mồi gi&uacute;p bản th&acirc;n đặc biệt hơn hẳn c&aacute;c con slime th&ocirc;ng thường nhưng Rimuru lại chưa nhận ra điều đ&oacute;, anh sẽ l&agrave;m g&igrave; để bảo vệ bản th&acirc;n v&agrave; thực hiện được mục ti&ecirc;u &ldquo;ăn sạch&rdquo; của m&igrave;nh trong thế giới đầy rẫy những hiểm nguy n&agrave;y?</p>
 <p>&ldquo;Về chuyện t&ocirc;i chuyển sinh th&agrave;nh Slime&rdquo; l&agrave; series light novel được chắp b&uacute;t bởi Fuse v&agrave; vẽ minh họa bởi Mizt Vah đ&atilde; g&acirc;y được tiếng vang lớn với 20 triệu bản s&aacute;ch được b&aacute;n ra tại Nhật. C&ugrave;ng nội dung l&ocirc;i cuốn v&agrave; phần minh họa đỉnh cao, series đ&igrave;nh đ&aacute;m n&agrave;y hứa hẹn sẽ đưa người đọc v&agrave;o một cuộc h&agrave;nh tr&igrave;nh hồi hộp hấp dẫn đến nghẹt thở ngay từ tập đầu ti&ecirc;n!<br />
 <br />
 &nbsp;</p>
 <p>Gi&aacute; sản phẩm tr&ecirc;n Tiki đ&atilde; bao gồm thuế theo luật hiện h&agrave;nh. Tuy nhi&ecirc;n tuỳ v&agrave;o từng loại sản phẩm hoặc phương thức, địa chỉ giao h&agrave;ng m&agrave; c&oacute; thể ph&aacute;t sinh th&ecirc;m chi ph&iacute; kh&aacute;c như ph&iacute; vận chuyển, phụ ph&iacute; h&agrave;ng cồng kềnh, ...</p>
 ',1,30,93150,31,135000, 0,4,1,'Fuse');
insert into tbl_sanpham(id,nameProduct,imgProduct, describes, status, quantity, discount, percentDiscount, price, view, idDM,idNCC,author)
values(9,'LĂN VÀO BẾP','bikipnauanlanvaobep1-468x500.jpg','<p style="text-align: justify;">Nấu ăn với người này là một góc yêu thương, là thư giãn, là tài năng hay sở thích. Nhưng đối với nhiều người thì nấu ăn là cả một Thử Thách Khó Khăn hay Nỗi Kinh Hoàng Khó Nói. Làm thế nào để công việc nấu ăn trở nên dễ thở hơn với những người không có năng khiếu hay lười biếng, hoặc vừa lười vừa thường gây thảm họa (như cánh họa sĩ chẳng hạn)? Đừng lo, câu hỏi đó không còn là câu hỏi tu từ nữa mà đã có lời giải đáp cho bạn ngay ở đây.</p>
<p style="text-align: justify;">Mọi thứ liên quan đến bếp núc đều có bí quyết riêng để xử lý, nếu bạn nắm được những bí quyết nho nhỏ này thì hãy an tâm là bạn đã thành công một phần rồi đó. Phần còn lại phụ thuộc vào quyết tâm (hay lý do!?) lăn vào bếp của bạn. Dù bạn học nấu ăn vì bị ép buộc, bị cưỡng chế, bị dụ dỗ, hay rảnh quá nên nghía chơi chút, hay bất cứ lý do nào, hãy cùng biến công cuộc vào bếp thành những khám phá thú vị và mới lạ.</p>
<p style="text-align: justify;">Cùng trải nghiệm những mẹo vặt nấu nướng, những công thức nấu ăn đơn giản và những loại thực phẩm cải thiện tính cách có trong Bí kíp nấu ăn: Lăn vào bếp của hai họa sĩ siêu lười, siêu đoảng của Cloud Pillow Studio. Một cuốn sách dễ thương, đầy màu sắc, vui nhộn, thú vị, bổ ích và cần có trên giá sách, bên kệ bếp và trên bàn ăn của bạn.</p>
',1,15,56000,25,75000,0,1,1,'');
insert into tbl_sanpham(id,nameProduct,imgProduct, describes, status, quantity, discount, percentDiscount, price, view, idDM,idNCC,author)
values(10,'Nghệ Thuật Để Giao Tiếp Thành Công Nơi Công Sở','dd708280e1e1ed35508afee26b7e3749.jpg','<h2>Nghệ Thuật Để Giao Tiếp Th&agrave;nh C&ocirc;ng Nơi C&ocirc;ng Sở</h2>
 <p>T&aacute;c giả s&aacute;ch b&aacute;n chạy&nbsp;<strong><em>Nghệ thuật giao tiếp để th&agrave;nh c&ocirc;ng</em></strong>&nbsp;đem đến trong t&aacute;c phẩm tiếp theo &ndash;&nbsp;<strong><em>Nghệ thuật giao tiếp để th&agrave;nh c&ocirc;ng nơi c&ocirc;ng sở</em>.</strong></p>
 <p>Mỗi người ch&uacute;ng ta đều phải đối mặt với những t&igrave;nh huống kh&oacute; khăn trong giao tiếp mỗi ng&agrave;y, cả tr&ecirc;n mạng lẫn gặp gỡ trực tiếp &ndash; vị sếp x&eacute;t n&eacute;t, đồng nghiệp xấu t&iacute;nh, mưu kế ch&iacute;nh trị nơi c&ocirc;ng sở c&ugrave;ng nhiều thứ kh&aacute;c nữa. Cuốn s&aacute;ch&nbsp;<strong>Nghệ Thuật Để Giao Tiếp Th&agrave;nh C&ocirc;ng Nơi C&ocirc;ng Sở</strong>&nbsp;ghi lại 72 thủ thuật c&oacute; thể &aacute;p dụng ngay lập tức v&agrave; c&oacute; hiệu quả r&otilde; rệt để giải quyết những vấn đề đ&oacute;. Để th&agrave;nh c&ocirc;ng, bạn cần c&oacute; trong m&igrave;nh những phẩm chất quan trọng sau:</p>
 <p><strong>Tự tin</strong><strong>&nbsp;(Confidence):&nbsp;</strong>10 c&aacute;ch để cấp tr&ecirc;n v&agrave; đồng nghiệp thấy bạn tự tin 100% v&agrave; c&oacute; thể đạt được bất cứ điều g&igrave; bạn muốn, đồng thời củng cố ấn tượng n&agrave;y trong to&agrave;n bộ mối quan hệ c&ocirc;ng việc của bạn</p>
 <p><strong>Quan t&acirc;m (Caring):&nbsp;&nbsp;</strong>14 chiến lược để thể hiện sự quan t&acirc;m của bạn đến đồng nghiệp v&agrave; c&ocirc;ng ty v&igrave; &ldquo;mọi người kh&ocirc;ng quan t&acirc;m đến việc bạn biết những g&igrave; cho đến khi họ biết bạn quan t&acirc;m ở mức độ n&agrave;o&rdquo;.</p>
 <p><strong>R&agrave;nh mạch</strong><strong>&nbsp;(Clarity):&nbsp;</strong>12 kỹ thuật gi&uacute;p bạn tr&igrave;nh b&agrave;y &yacute; tưởng r&otilde; r&agrave;ng v&agrave; đảm bảo mọi người bạn l&agrave;m việc c&ugrave;ng đều hiểu &yacute; tưởng ấy.</p>
 <p><strong>Uy t&iacute;n</strong><strong>&nbsp;(Credibility):&nbsp;</strong>14 phương ph&aacute;p để chiếm được l&ograve;ng tin v&agrave; sự t&ocirc;n trọng của mọi người trong c&ocirc;ng ty của bạn v&agrave; g&acirc;y ấn tượng với người kh&aacute;c qua Internet.</p>
 <p><strong>Chung sống</strong><strong>&nbsp;(Coexistence)</strong><strong>&nbsp;(với những</strong><strong>&nbsp;vị</strong><strong>&nbsp;sếp th&ocirc; lỗ v&agrave; đ&aacute;m đồng nghiệp đi&ecirc;n rồ)</strong>): 21 chiến thuật để đương đầu với cơn &aacute;c mộng số một tại nơi l&agrave;m việc v&agrave; &ldquo;tỏa s&aacute;ng&rdquo;.</p>
 <p><strong>NHẬN X&Eacute;T CỦA ĐỘC GIẢ UY T&Iacute;N</strong></p>
 <p>&ldquo;Cuốn s&aacute;ch đầy thuyết phục v&agrave; thực tế n&agrave;y sẽ chỉ cho bạn c&aacute;ch l&agrave;m thế n&agrave;o để tạo ảnh hưởng l&ecirc;n người kh&aacute;c, truyền đạt &yacute; tưởng mạch lạc v&agrave; đạt được mục đ&iacute;ch của m&igrave;nh th&ocirc;ng qua người kh&aacute;c nhanh hơn bao giờ hết.&rdquo; &mdash; Brian Tracy&nbsp;</p>
 <p>&ldquo;Để tr&aacute;nh gặp thất bại trong c&ocirc;ng việc ngay từ khi bắt đầu sự nghiệp, ai cũng n&ecirc;n đọc cuốn s&aacute;ch n&agrave;y của Leil Lowndes. Kết cấu chặt chẽ, nghi&ecirc;n cứu thấu đ&aacute;o v&agrave; nội dung thực tiễn &ndash; đ&acirc;y l&agrave; một cuốn s&aacute;ch vui nhộn, dễ đọc, dễ hiểu c&ugrave;ng c&aacute;c mẹo v&agrave; lời khuy&ecirc;n m&agrave; ai cũng c&oacute; thể v&agrave; n&ecirc;n &aacute;p dụng ngay!&rdquo; &mdash; Gregory Giangrande, phụ tr&aacute;ch chuy&ecirc;n mục hướng nghiệp của&nbsp;<em>New York Post</em></p>
 <p>&ldquo;Cuốn s&aacute;ch tuyệt vời v&agrave; v&ocirc; c&ugrave;ng th&uacute; vị n&agrave;y sẽ m&aacute;ch bạn c&aacute;ch vươn tới đỉnh cao m&agrave; kh&ocirc;ng khiến bất kỳ ai trở th&agrave;nh địch thủ tr&ecirc;n con đường tiến bước!&rdquo; &mdash; Marshall Goldsmith, nằm trong danh s&aacute;ch &ldquo;Những nh&agrave; tư tưởng l&atilde;nh đạo c&oacute; tầm ảnh hưởng nhất thế giới&ldquo; của Thinkers50</p>
 <p>&ldquo;<em>Nghệ thuật giao tiếp để th&agrave;nh c&ocirc;ng nơi c&ocirc;ng sở</em>&nbsp;ch&iacute;nh l&agrave; cuốn cẩm nang về b&iacute; quyết th&agrave;nh c&ocirc;ng trong c&ocirc;ng việc v&agrave; cuộc sống. C&aacute;c nguy&ecirc;n tắc trong cuốn s&aacute;ch được x&acirc;y dựng dựa tr&ecirc;n sự tự tin, cho người kh&aacute;c thấy rằng bạn quan t&acirc;m, giao tiếp minh bạch, sự ch&acirc;n th&agrave;nh để tạo dựng niềm tin v&agrave; th&aacute;i độ ki&ecirc;n nhẫn khi chung sống với đồng nghiệp. Cuốn s&aacute;ch ph&ugrave; hợp với c&aacute;c nghi&ecirc;n cứu của ch&uacute;ng t&ocirc;i v&agrave; ch&uacute;ng t&ocirc;i khuyến kh&iacute;ch bạn n&ecirc;n luyện tập ch&uacute;ng, đặc biệt l&agrave; nội dung về kh&iacute;a cạnh phi ng&ocirc;n ngữ v&agrave; yếu tố thị gi&aacute;c trong giao tiếp để người kh&aacute;c c&oacute; thể tin tưởng, trung thực v&agrave; tự nguyện gắn b&oacute; với bạn.&rdquo; &mdash; Peter J. Dean v&agrave; Molly D. Shepard, t&aacute;c giả cuốn&nbsp;<em>The Bully-Proof Workplace</em>&nbsp;(tạm dịch: Để tr&aacute;nh bị bắt nạt tại nơi l&agrave;m việc)</p>
 <p><strong>VỀ T&Aacute;C GIẢ</strong></p>
 <p><strong>Leil Lowndes</strong>&nbsp;hiện l&agrave; một trong những chuy&ecirc;n gia giao tiếp được quốc tế c&ocirc;ng nhận. B&agrave; được mời l&agrave;m diễn giả tại c&aacute;c sự kiện ở nhiều th&agrave;nh phố lớn của Mỹ, cũng như c&aacute;c c&ocirc;ng ty v&agrave; tập đo&agrave;n lớn. B&agrave; cũng l&agrave; t&aacute;c giả của nhiều cuốn s&aacute;ch b&aacute;n chạy như Nghệ thuật giao tiếp để th&agrave;nh c&ocirc;ng, How to make anyone fall in love with you (tạm dịch: L&agrave;m thế n&agrave;o để khiến mọi người y&ecirc;u qu&yacute; bạn).</p>
 <h1>Nghệ Thuật Giao Tiếp Để Th&agrave;nh C&ocirc;ng</h1>
 <p>Nghệ thuật giao tiếp để th&agrave;nh c&ocirc;ng hướng tới mọi đối tượng độc giả, d&ugrave; l&agrave; sinh vi&ecirc;n, nh&acirc;n vi&ecirc;n b&aacute;n h&agrave;ng, doanh nh&acirc;n, nh&agrave; quản l&yacute;, ch&iacute;nh trị gia hay người nội trợ hoặc bất cứ ai muốn kiểm so&aacute;t c&aacute;c mối quan hệ, thu nhập hay cuộc đời họ theo c&aacute;ch hiệu quả hơ</p>
 <p>Họ l&agrave; người c&oacute; c&ocirc;ng việc tốt nhất, c&oacute; người bạn đời tuyệt vời nhất, c&oacute; nhiều bạn b&egrave; tốt v&agrave; c&oacute; t&agrave;i khoản thật lớn trong ng&acirc;n h&agrave;ng.</p>
 <p>V&igrave; sao họ đạt được những điều đ&oacute;? Phải chăng họ c&oacute; đ&ocirc;i tay của vua midas chạm v&agrave;o bất cứ đ&acirc;u mọi thứ đều biến th&agrave;nh v&agrave;ng? Hay họ được ban tặng nhiều hơn? Kh&ocirc;ng phải vậy. Nhiều người trong số họ kh&ocirc;ng hề th&ocirc;ng minh hơn, thậm ch&iacute; cũng chẳng ưa nh&igrave;n hơn bạn! Sự thật những người th&agrave;nh đạt như vậy thường c&oacute; khả năng giao tiếp, ứng xử kh&eacute;o l&eacute;o hơn người kh&aacute;c. Sự thật kh&aacute;c c&oacute; thể khiến bạn ngạc nhi&ecirc;n l&agrave; ai trong ch&uacute;ng ta cũng tiềm ẩn khả năng n&agrave;y, chỉ c&oacute; điều l&agrave; người c&oacute; nhiều, người c&oacute; &iacute;t m&agrave; th&ocirc;i.</p>
 <p>Trong Nghệ thuật giao tiếp để th&agrave;nh c&ocirc;ng, với 92 thủ thuật đơn giản m&agrave; hiệu quả, Leil Lowndes sẽ gi&uacute;p bạn kh&aacute;m ph&aacute; v&agrave; r&egrave;n luyện c&aacute;c kỹ năng để:</p>
 <ul>
 	<li>Tạo một khởi đầu ấn tượng v&agrave; gặp được những người bạn muốn;</li>
 	<li>H&ograve;a nhập linh hoạt v&agrave;o bất cứ nh&oacute;m n&agrave;o, d&ugrave; giữa bạn v&agrave; họ &iacute;t tương đồng đến đ&acirc;u;</li>
 	<li>Sử dụng ng&ocirc;n ngữ cơ thể để l&ocirc;i cuốn người nghe;</li>
 	<li>Trở th&agrave;nh nh&acirc;n vật trung t&acirc;m tại mọi bữa tiệc;</li>
 	<li>Lu&ocirc;n tự tin, đ&aacute;ng tin cậy v&agrave; g&acirc;y ảnh hưởng ở mọi nơi m&agrave; bạn đến.</li>
 </ul>
 <p>Gi&aacute; sản phẩm tr&ecirc;n Tiki đ&atilde; bao gồm thuế theo luật hiện h&agrave;nh. Tuy nhi&ecirc;n tuỳ v&agrave;o từng loại sản phẩm hoặc phương thức, địa chỉ giao h&agrave;ng m&agrave; c&oacute; thể ph&aacute;t sinh th&ecirc;m chi ph&iacute; kh&aacute;c như ph&iacute; vận chuyển, phụ ph&iacute; h&agrave;ng cồng kềnh, ...</p>
 ',1,20,349680,6,372000,0,1,7,'');
insert into tbl_sanpham(id,nameProduct,imgProduct, describes, status, quantity, discount, percentDiscount, price, view, idDM,idNCC,author)
values(11,'Sword Art Online: Alicization Invading','7d1b0f2a2805ffab2da7994630043f73.jpg','<p>&ldquo;Kirito, cho tớ biết, tớ phải l&agrave;m sao mới được đ&acirc;y?&rdquo;</p>
 
 <p>C&aacute;i gi&aacute; phải trả của việc đ&aacute;nh bại tư tế tối cao Administrator, l&agrave; c&aacute;i chết của Eugeo, v&agrave; trạng th&aacute;i tinh thần suy sụp của Kirito.</p>
 
 <p>Đ&atilde; nửa năm tr&ocirc;i qua từ trận chiến t&agrave;n khốc ấy.</p>
 
 <p>Alice đưa Kirito về lại l&agrave;ng Rulid. Bấy giờ cậu đ&atilde; kh&ocirc;ng c&ograve;n &yacute; ch&iacute; g&igrave; nữa, vẻ mặt th&igrave; trống rỗng, người lại ngồi tr&ecirc;n xe lăn.</p>
 
 <p>Trao trả nhiệm vụ bảo vệ Nh&acirc;n giới cho Bercouli, Alice chọn lựa sống đời y&ecirc;n ả c&ugrave;ng Kirito. Nhưng giai đoạn phụ tải cuối, như nh&agrave; hiền triết Cardinal ti&ecirc;n đo&aacute;n, đang từng bước &aacute;p s&aacute;t&hellip;</p>
 
 <p>Bầu kh&ocirc;ng kh&iacute; t&agrave; &aacute;c từ Vương quốc B&oacute;ng tối bắt đầu tr&agrave;n sang Nh&acirc;n giới. Qu&acirc;n đo&agrave;n B&oacute;ng tối khủng khiếp cuối c&ugrave;ng cũng đ&atilde; rục rịch h&agrave;nh động.</p>
 
 <p>Gi&aacute; sản phẩm tr&ecirc;n Tiki đ&atilde; bao gồm thuế theo luật hiện h&agrave;nh. Tuy nhi&ecirc;n tuỳ v&agrave;o từng loại sản phẩm hoặc phương thức, địa chỉ giao h&agrave;ng m&agrave; c&oacute; thể ph&aacute;t sinh th&ecirc;m chi ph&iacute; kh&aacute;c như ph&iacute; vận chuyển, phụ ph&iacute; h&agrave;ng cồng kềnh, ...</p>
 ',1,30,93750,25,125000,0,4,6,'');
insert into tbl_sanpham(id,nameProduct,imgProduct, describes, status, quantity, discount, percentDiscount, price, view, idDM,idNCC,author)
values(12,'Sword Art Online Progressive 005','53c5d8661fdabb410f0d1125920e7dd6.png','<div><p style="font-weight: 400;">Sau cuộc chạm trán đầy hung hiểm với Người áo choàng đen, Kirito và Asuna đã công phá được tầng 5 Aincrad!</p>
<p style="font-weight: 400;">“Phải luôn luôn có mặt ở nơi tôi nhìn thấy được, rõ chưa!”</p>
<p style="font-weight: 400;">Do số phận đưa đẩy, hai người suốt ngày cặp kè bên nhau, và tiếp theo họ sẽ đối mặt với những thách thức phải huy động đến trí tuệ ở tầng 6.</p>
<p style="font-weight: 400;">Ngoài ra còn phải giành lấy The Flag of Valor, một item có khả năng phá vỡ thế cân bằng cũng như mang tính uy hiếp với cả hai guild lớn.</p>
<p style="font-weight: 400;">Dù gặp bao nhiêu vấn đề&nbsp;như&nbsp;vậy, hai người vẫn tiếp tục quest Lời nguyền Stachion&nbsp;ở&nbsp;tầng 6 mà không biết nguy hiểm đang rình rập họ.</p><p>Giá sản phẩm trên Tiki đã bao gồm thuế theo luật hiện hành. Tuy nhiên tuỳ vào từng loại sản phẩm hoặc phương thức, địa chỉ giao hàng mà có thể phát sinh thêm chi phí khác như phí vận chuyển, phụ phí hàng cồng kềnh, ...</p></div>',
1,20,90000,25,120000,0,4,6,'' );
insert into tbl_sanpham(id,nameProduct,imgProduct, describes, status, quantity, discount, percentDiscount, price, view, idDM,idNCC,author)
values(13, 'Sword Art Online 014 (Bản Thông Thường)','3fb174c5a5ec493140b543ec1cedcfc7.jpg','<div><p>Tòa tháp trắng Central Cathedral tượng trưng cho Giáo hội Công lý.</p>
<p>Nhờ sự giúp đỡ của Cardinal, nhà hiền triết bị cách li trong tàng thư các, Eugeo và Kirito bắt đầu hành trình lên tầng 100, tầng cao nhất của Cathedral, nơi ở của tư tế tối cao Administrator.</p>
<p>Mục đích của Eugeo là lấy lại “nguyên bản” cho Alice, nay đã bị biến thành Hiệp sĩ Chỉnh hợp, còn mục đích của Kirito là để cứu rỗi Underworld khỏi sự diệt vong.</p>
<p>Họ đã đến tầng 99.</p>
<p>Xuất hiện trước mắt Kirito và Alice lại là Eugeo. Nhưng là một Eugeo mặc giáp Hiệp sĩ Chỉnh hợp và đôi mắt lóe lên lạnh giá.</p>
<p>Eugeo phũ phàng vung kiếm, Kirito bất đắc dĩ phải đánh trả.</p>
<p>Lẽ nào điềm báo về trận chiến và li biệt mà cậu cảm nhận được trong tiếng sấm xa xăm vào ngày đầu khởi hành khỏi làng đã thành sự thật? Tiếng gọi thiết tha của Kirito liệu có lay chuyển được một Eugeo đã bị phong ấn kí ức?</p>
<p>Alicization, phần “Nhân giới”, kết thúc!</p><p>Giá sản phẩm trên Tiki đã bao gồm thuế theo luật hiện hành. Tuy nhiên tuỳ vào từng loại sản phẩm hoặc phương thức, địa chỉ giao hàng mà có thể phát sinh thêm chi phí khác như phí vận chuyển, phụ phí hàng cồng kềnh, ...</p></div>',
1,20,93750,25,125000,0,4,6,'' );

insert into tbl_sanpham(id,nameProduct,imgProduct, describes, status, quantity, discount, percentDiscount, price, view, idDM,idNCC,author)
values(14, 'Sword Art Online 003:Fairy Dance','sao3 cover 1.u335.d20160411.t145256_2.jpg','<div><p style="text-align: justify;"><span style="color: #ff6600; font-size: medium;"><strong>Sword Art Online (Tập 3)</strong></span></p>
<p style="text-align: justify;">Rời trò chơi sinh tử Sword Art Online trở về hiện thực, Kirito lập tức đi tìm những người bạn kề vai sát cánh với mình trong trò chơi ấy. Dĩ nhiên cũng ráo riết kiếm tìm dấu vết người vợ yêu quý Asuna. Nhưng hóa ra Asuna vẫn chưa thoát thân được khỏi trò chơi.</p>
<p style="text-align: justify;">Hoàn toàn không hiểu tình hình này là thế nào, Kirito không khỏi sinh lòng tuyệt vọng. Manh mối duy nhất của cậu là một file ảnh lạ lùng cho thấy Asuna đứng trong một chiếc lồng với hình dạng “tinh linh”. Dường như cô đang bị giam hãm Alfheim Online, một trò chơi VRMMO tính năng cao.</p>
<p style="text-align: justify;">Để giải cứu Asuna, Kirito lao vào thế giới ALO đông đảo tinh linh ấy.</p>
<p style="text-align: justify;">Và câu chuyện Fairy Dance bắt đầu…</p><p>Giá sản phẩm trên Tiki đã bao gồm thuế theo luật hiện hành. Tuy nhiên tuỳ vào từng loại sản phẩm hoặc phương thức, địa chỉ giao hàng mà có thể phát sinh thêm chi phí khác như phí vận chuyển, phụ phí hàng cồng kềnh, ...</p></div>'
,1,30,76000,20,95000,0,4,6,'');
insert into tbl_sanpham(id,nameProduct,imgProduct, describes, status, quantity, discount, percentDiscount, price, view, idDM,idNCC,author)
values(15,'Sherlock Holmes Toàn Tập','a4fececbba40be27dbfd32ca66b0a6f1.jpg','<div><h3>Sherlock Holmes Toàn Tập</h3>
Cái tên Sherlock Holmes đã quen thuộc khắp thế giới tới mức một người dù có thể chưa hề đọc truyện về nhà thám tử này nhưng chỉ cần nghe tên cũng biết anh ta là ai. Sherlock Holmes đã trở thành một biểu tượng của văn hóa đại chúng toàn cầu. Khác với những nhân vật thần tượng chỉ vang bóng một thời, Sherlock Holmes kể từ khi xuất hiện lần đầu tiên năm 1887 qua sáng tạo của Sir Arthur Conan Doyle vẫn sống mãi qua ba thế kỉ.
Sherlock Holmes hiện lên qua lời kể của cộng sự thân thiết và người viết tiểu sử tận tụy - bác sĩ Watson như một chân dung độc đáo, là chuyên gia số một trong lĩnh vực điều tra hình sự và khoa học suy luận, "chiến sĩ bảo vệ công lí lỗi lạc nhất" của thời đại. Trong sự nghiệp truy lùng tội phạm, vị thám tử đại tài từng trải qua nhiều thử thách gay cấn, thậm chí đã một lần chết đi sống lại, nhưng cũng chính nhờ đó, Holmes trở thành một nhân vật bất tử, được độc giả khắp thế giới yêu mến vì tài trí và chất nghệ sĩ, vì cả những nhược điểm lẫn cá tính lập dị.
<br>Bản dịch mới này tiếp cận tác phẩm của Doyle trên&nbsp; cả&nbsp; góc&nbsp; độ&nbsp; lịch&nbsp; sử&nbsp; và&nbsp; văn&nbsp; chương, không xem&nbsp; toàn&nbsp; tập&nbsp; Sherlock Holmes như những truyện trinh thám phổ thông mà là một danh tác kinh điển. Bộ Sherlock Holmes toàn tập 3 tập, bìa mềm, hộp ngang có thêm Phụ bản in màu ở cuối tập 3 về Bảo tàng Sherlock Holmes.
Nội dung từng tập:
Tập 1
Sherlock Holmes lần đầu ra mắt công chúng trong một vụ án mạng hóc hiểm với tựa đề Cuộc điều tra màu đỏ (1887). Đây là khởi điểm của tình bạn lâu bền giữa Sherlock Holmes và bác sĩ Watson mà rồi đây sẽ làm đổi thay lịch sử loại hình tiểu thuyết trinh thám. Tiếp đó, trong Dấu bộ tứ (1890), đôi bạn Holmes và Watson tái xuất trong một vụ án mạng không kém phần li kì, phức tạp. Hai thiên truyện đầu ấy, hiện lên sinh động qua lời kể của bác sĩ Watson, không chỉ giới thiệu với độc giả phương pháp điều tra và suy luận của nhà thám tử tài ba mà còn góp phần định hình phong cách cho những truyện Sherlock Holmes sáng tác sau này.
Tập 2
Tập truyện ngắn thứ hai Những hồi ức về Sherlock Holmes (1894) mở ra cho độc giả cái nhìn toàn diện hơn về một Sherlock Holmes sở hữu nhiều năng lực xuất chúng nhưng cũng vô cùng lập dị. Cũng trong loạt truyện này, độc giả được hé lộ về vụ án đầu tiên đã tạo nên bước ngoặt đưa Holmes vào sự nghiệp thám tử; nhưng đáng nhớ nhất có lẽ là Vụ án cuối cùng, cuộc đối đầu gay cấn giữa Holmes và đối thủ nguy hiểm nhất trong giới tội phạm - giáo sư Moriarty.
Tập 3
Khởi đầu từ một vụ án lắt léo tại vùng quê Anh quốc, Thung lũng Kinh hoàng (1915) đưa độc giả tới một vùng mỏ của Hoa Kì - sân khấu u ám cho những mưu mô, những cuộc đấu đá, thanh trừng, khủng bố của một băng đảng đã gieo rắc nỗi khiếp sợ cho biết bao con người. Cách dẫn dắt truyện ở đây gợi nhớ đến hai đoản thiên tiểu thuyết đầu cũng gắn với những vụ án có căn nguyên sâu xa từ hàng chục năm về trước.<p>Giá sản phẩm trên Tiki đã bao gồm thuế theo luật hiện hành. Tuy nhiên tuỳ vào từng loại sản phẩm hoặc phương thức, địa chỉ giao hàng mà có thể phát sinh thêm chi phí khác như phí vận chuyển, phụ phí hàng cồng kềnh, ...</p></div>',
1,30,562500,25,750000,0,5,6,'');
insert into tbl_sanpham(id,nameProduct,imgProduct, describes, status, quantity, discount, percentDiscount, price, view, idDM,idNCC,author)
values(16,'Đề Thi Đẫm Máu','a195fe8af22c6d529681eaaaf7de31ac.jpg','<div class="content"><div class="ToggleContent__Wrapper-sc-1hm81e2-1 iGyNLs"><div class="ToggleContent__View-sc-1hm81e2-0 eIzUuC"><div><p>Một tên sát thủ có sở thích uống chất hỗn hợp máu nạn nhân với sữa tươi, hắn có căn bệnh gì đặc biệt hay là con quỷ hút máu bất tử nghìn năm trong truyền thuyết?</p>
<p>Trong thành phố C liên tiếp xảy ra 4 vụ cưỡng hiếp giết người, nạn nhân đều là những cô gái trí thức từ 25 - 35 tuổi, đây rốt cuộc là giết người trả thù hay đơn giản là cưỡng dâm?</p>
<p>Hàng loạt cái chết bí ẩn thảm khốc của những người sống trong trường Đại học J liên tiếp xảy ra. Ở hiện trường vụ án, hung thủ đều để lại gợi ý cho vụ án tiếp theo, nhằm gợi ý gì?</p>
<p>Trong hàng loạt các vụ án ly kỳ khiến cảnh sát bàng hoàng bó tay, Phương Mộc trầm mặc kiệm lời đột nhiên bị cảnh sát lôi vào cuộc. Tên ác quỷ giấu mặt lần lượt giết hại những người bạn của cậu, vì sao? Khi câu trả lời được vén màn bí mật, thì đề thi tàn khốc đã bị tích 5 dấu X đẫm máu.</p>
<p>Một cuộc đấu trí so tài khốc liệt đầy kịch tính nổ Ai sẽ là người thắng cuộc?</p>
<p>Đây là tác phẩm trinh thám được nhiều người biết đến nhất của Lôi Mễ - sĩ quan cảnh sát cấp phòng (sở) giảng dạy bộ môn Hình pháp học tại một trường cảnh sát trực thuộc Bộ Công an Trung Quốc, đồng thời cũng là một tác giả truyện trinh thám nổi tiếng. Truyện của Lôi Mễ luôn có sức hấp dẫn đặc biệt đối với độc giả bởi ngòi bút sắt bén với những tình tiết ly kì, lôi cuốn đến trang cuối cùng.</p><p>Giá sản phẩm trên Tiki đã bao gồm thuế theo luật hiện hành. Tuy nhiên tuỳ vào từng loại sản phẩm hoặc phương thức, địa chỉ giao hàng mà có thể phát sinh thêm chi phí khác như phí vận chuyển, phụ phí hàng cồng kềnh, ...</p></div></div></div></div>',
1,30,128500,11,145000,0,5,8,'');

insert into tbl_sanpham(id,nameProduct,imgProduct, describes, status, quantity, discount, percentDiscount, price, view, idDM,idNCC,author)
values(17,'Sherlock Holmes Toàn Tập','a4fececbba40be27dbfd32ca66b0a6f1.jpg','<div><h3>Sherlock Holmes Toàn Tập</h3>
Cái tên Sherlock Holmes đã quen thuộc khắp thế giới tới mức một người dù có thể chưa hề đọc truyện về nhà thám tử này nhưng chỉ cần nghe tên cũng biết anh ta là ai. Sherlock Holmes đã trở thành một biểu tượng của văn hóa đại chúng toàn cầu. Khác với những nhân vật thần tượng chỉ vang bóng một thời, Sherlock Holmes kể từ khi xuất hiện lần đầu tiên năm 1887 qua sáng tạo của Sir Arthur Conan Doyle vẫn sống mãi qua ba thế kỉ.
Sherlock Holmes hiện lên qua lời kể của cộng sự thân thiết và người viết tiểu sử tận tụy - bác sĩ Watson như một chân dung độc đáo, là chuyên gia số một trong lĩnh vực điều tra hình sự và khoa học suy luận, "chiến sĩ bảo vệ công lí lỗi lạc nhất" của thời đại. Trong sự nghiệp truy lùng tội phạm, vị thám tử đại tài từng trải qua nhiều thử thách gay cấn, thậm chí đã một lần chết đi sống lại, nhưng cũng chính nhờ đó, Holmes trở thành một nhân vật bất tử, được độc giả khắp thế giới yêu mến vì tài trí và chất nghệ sĩ, vì cả những nhược điểm lẫn cá tính lập dị.
<br>Bản dịch mới này tiếp cận tác phẩm của Doyle trên&nbsp; cả&nbsp; góc&nbsp; độ&nbsp; lịch&nbsp; sử&nbsp; và&nbsp; văn&nbsp; chương, không xem&nbsp; toàn&nbsp; tập&nbsp; Sherlock Holmes như những truyện trinh thám phổ thông mà là một danh tác kinh điển. Bộ Sherlock Holmes toàn tập 3 tập, bìa mềm, hộp ngang có thêm Phụ bản in màu ở cuối tập 3 về Bảo tàng Sherlock Holmes.
Nội dung từng tập:
Tập 1
Sherlock Holmes lần đầu ra mắt công chúng trong một vụ án mạng hóc hiểm với tựa đề Cuộc điều tra màu đỏ (1887). Đây là khởi điểm của tình bạn lâu bền giữa Sherlock Holmes và bác sĩ Watson mà rồi đây sẽ làm đổi thay lịch sử loại hình tiểu thuyết trinh thám. Tiếp đó, trong Dấu bộ tứ (1890), đôi bạn Holmes và Watson tái xuất trong một vụ án mạng không kém phần li kì, phức tạp. Hai thiên truyện đầu ấy, hiện lên sinh động qua lời kể của bác sĩ Watson, không chỉ giới thiệu với độc giả phương pháp điều tra và suy luận của nhà thám tử tài ba mà còn góp phần định hình phong cách cho những truyện Sherlock Holmes sáng tác sau này.
Tập 2
Tập truyện ngắn thứ hai Những hồi ức về Sherlock Holmes (1894) mở ra cho độc giả cái nhìn toàn diện hơn về một Sherlock Holmes sở hữu nhiều năng lực xuất chúng nhưng cũng vô cùng lập dị. Cũng trong loạt truyện này, độc giả được hé lộ về vụ án đầu tiên đã tạo nên bước ngoặt đưa Holmes vào sự nghiệp thám tử; nhưng đáng nhớ nhất có lẽ là Vụ án cuối cùng, cuộc đối đầu gay cấn giữa Holmes và đối thủ nguy hiểm nhất trong giới tội phạm - giáo sư Moriarty.
Tập 3
Khởi đầu từ một vụ án lắt léo tại vùng quê Anh quốc, Thung lũng Kinh hoàng (1915) đưa độc giả tới một vùng mỏ của Hoa Kì - sân khấu u ám cho những mưu mô, những cuộc đấu đá, thanh trừng, khủng bố của một băng đảng đã gieo rắc nỗi khiếp sợ cho biết bao con người. Cách dẫn dắt truyện ở đây gợi nhớ đến hai đoản thiên tiểu thuyết đầu cũng gắn với những vụ án có căn nguyên sâu xa từ hàng chục năm về trước.<p>Giá sản phẩm trên Tiki đã bao gồm thuế theo luật hiện hành. Tuy nhiên tuỳ vào từng loại sản phẩm hoặc phương thức, địa chỉ giao hàng mà có thể phát sinh thêm chi phí khác như phí vận chuyển, phụ phí hàng cồng kềnh, ...</p></div>',
1,30,562500,25,750000,0,5,8,'');
insert into tbl_sanpham(id,nameProduct,imgProduct, describes, status, quantity, discount, percentDiscount, price, view, idDM,idNCC,author)
values(18, 'Sword Art Online 014 (Bản Thông Thường)','3fb174c5a5ec493140b543ec1cedcfc7.jpg','<div><p>Tòa tháp trắng Central Cathedral tượng trưng cho Giáo hội Công lý.</p>
<p>Nhờ sự giúp đỡ của Cardinal, nhà hiền triết bị cách li trong tàng thư các, Eugeo và Kirito bắt đầu hành trình lên tầng 100, tầng cao nhất của Cathedral, nơi ở của tư tế tối cao Administrator.</p>
<p>Mục đích của Eugeo là lấy lại “nguyên bản” cho Alice, nay đã bị biến thành Hiệp sĩ Chỉnh hợp, còn mục đích của Kirito là để cứu rỗi Underworld khỏi sự diệt vong.</p>
<p>Họ đã đến tầng 99.</p>
<p>Xuất hiện trước mắt Kirito và Alice lại là Eugeo. Nhưng là một Eugeo mặc giáp Hiệp sĩ Chỉnh hợp và đôi mắt lóe lên lạnh giá.</p>
<p>Eugeo phũ phàng vung kiếm, Kirito bất đắc dĩ phải đánh trả.</p>
<p>Lẽ nào điềm báo về trận chiến và li biệt mà cậu cảm nhận được trong tiếng sấm xa xăm vào ngày đầu khởi hành khỏi làng đã thành sự thật? Tiếng gọi thiết tha của Kirito liệu có lay chuyển được một Eugeo đã bị phong ấn kí ức?</p>
<p>Alicization, phần “Nhân giới”, kết thúc!</p><p>Giá sản phẩm trên Tiki đã bao gồm thuế theo luật hiện hành. Tuy nhiên tuỳ vào từng loại sản phẩm hoặc phương thức, địa chỉ giao hàng mà có thể phát sinh thêm chi phí khác như phí vận chuyển, phụ phí hàng cồng kềnh, ...</p></div>',
1,20,93750,25,125000,0,4,8,'' );

insert into tbl_sanpham(id,nameProduct,imgProduct, describes, status, quantity, discount, percentDiscount, price, view, idDM,idNCC,author)
values(19, 'Sword Art Online 003:Fairy Dance','sao3 cover 1.u335.d20160411.t145256_2.jpg','<div><p style="text-align: justify;"><span style="color: #ff6600; font-size: medium;"><strong>Sword Art Online (Tập 3)</strong></span></p>
<p style="text-align: justify;">Rời trò chơi sinh tử Sword Art Online trở về hiện thực, Kirito lập tức đi tìm những người bạn kề vai sát cánh với mình trong trò chơi ấy. Dĩ nhiên cũng ráo riết kiếm tìm dấu vết người vợ yêu quý Asuna. Nhưng hóa ra Asuna vẫn chưa thoát thân được khỏi trò chơi.</p>
<p style="text-align: justify;">Hoàn toàn không hiểu tình hình này là thế nào, Kirito không khỏi sinh lòng tuyệt vọng. Manh mối duy nhất của cậu là một file ảnh lạ lùng cho thấy Asuna đứng trong một chiếc lồng với hình dạng “tinh linh”. Dường như cô đang bị giam hãm Alfheim Online, một trò chơi VRMMO tính năng cao.</p>
<p style="text-align: justify;">Để giải cứu Asuna, Kirito lao vào thế giới ALO đông đảo tinh linh ấy.</p>
<p style="text-align: justify;">Và câu chuyện Fairy Dance bắt đầu…</p><p>Giá sản phẩm trên Tiki đã bao gồm thuế theo luật hiện hành. Tuy nhiên tuỳ vào từng loại sản phẩm hoặc phương thức, địa chỉ giao hàng mà có thể phát sinh thêm chi phí khác như phí vận chuyển, phụ phí hàng cồng kềnh, ...</p></div>'
,1,50,80000,20,100000,0,4,8,'');
insert into tbl_sanpham(id,nameProduct,imgProduct, describes, status, quantity, discount, percentDiscount, price, view, idDM,idNCC,author)
values(20,'Thám Tử Lừng Danh Conan Tập 98','4d4166c4fee360442889f320c84a12c5.jpg','<div><p>Sera Masumi tiếp tục thăm dò Haibara Ai và ở thế đối đầu với Okiya Subaru!</p>
<p>Trong khi đó, Conan đã tiến đến gần chân tướng của “em gái ngoài lãnh địa” - Mary…!?</p>
<p>Haneda Shukichi bất ngờ gặp án mạng tại buổi học nhóm shogi!</p>
<p>Vụ án diễn biến bất ngờ với nhiều khúc ngoặt để rồi cuối cùng, Akai Shuichi xuất hiện…!? Không dừng lại ở đó, tập 98 còn mang tới vụ án giải mật mã của một người giúp việc, nơi cuộc đua phá án giữa Conan và Heiji đã khởi phát từ mưu kế của Ooka Momiji!!<br><br></p><p>Giá sản phẩm trên Tiki đã bao gồm thuế theo luật hiện hành. Tuy nhiên tuỳ vào từng loại sản phẩm hoặc phương thức, địa chỉ giao hàng mà có thể phát sinh thêm chi phí khác như phí vận chuyển, phụ phí hàng cồng kềnh, ...</p></div>',
1,50,15700,22,20000,0,5,1,'' );
insert into tbl_sanpham(id,nameProduct,imgProduct, describes, status, quantity, discount, percentDiscount, price, view, idDM,idNCC,author)
values(21,'Thám Tử Lừng Danh Conan Tập 97','9b6a579e095939a7c9365752ecac72b4.jpg','<div>Conan, Mori Kogoro, Amuro Toru, và Wakita Kanenori.<br>
Bộ tứ kì lạ ấy cùng nhau đi tới một nhà thờ bỏ hoang ẩn mình trong núi sâu ở Nagano.<br>
Phải chăng chờ đợi họ ở đó là những án mạng và những mật mã bí ẩn!?<br>
Giữa lúc ấy, Conan cố gắng tìm kiếm gợi ý quan trọng liên quan tới chân tướng của “RUM” từ Amuro…!<br><p>Giá sản phẩm trên Tiki đã bao gồm thuế theo luật hiện hành. Tuy nhiên tuỳ vào từng loại sản phẩm hoặc phương thức, địa chỉ giao hàng mà có thể phát sinh thêm chi phí khác như phí vận chuyển, phụ phí hàng cồng kềnh, ...</p></div>',
1,50,15700,22,20000,0,5,1,'' );
insert into tbl_sanpham(id,nameProduct,imgProduct, describes, status, quantity, discount, percentDiscount, price, view, idDM,idNCC,author)
values(22,'Thám Tử Lừng Danh Conan Tập 96','9b6a579e095939a7c9365752ecac72b4.jpg','<div>Conan, Mori Kogoro, Amuro Toru, và Wakita Kanenori.<br>
Bộ tứ kì lạ ấy cùng nhau đi tới một nhà thờ bỏ hoang ẩn mình trong núi sâu ở Nagano.<br>
Phải chăng chờ đợi họ ở đó là những án mạng và những mật mã bí ẩn!?<br>
Giữa lúc ấy, Conan cố gắng tìm kiếm gợi ý quan trọng liên quan tới chân tướng của “RUM” từ Amuro…!<br><p>Giá sản phẩm trên Tiki đã bao gồm thuế theo luật hiện hành. Tuy nhiên tuỳ vào từng loại sản phẩm hoặc phương thức, địa chỉ giao hàng mà có thể phát sinh thêm chi phí khác như phí vận chuyển, phụ phí hàng cồng kềnh, ...</p></div>',
1,50,15700,22,20000,0,5,1,'' );
insert into tbl_sanpham(id,nameProduct,imgProduct, describes, status, quantity, discount, percentDiscount, price, view, idDM,idNCC,author)
values(23,'Thám Tử Lừng Danh Conan Tập 95','5a6c39c0b9229088a765de43cfd79838.jpg','<div>Thám Tử Lừng Danh Conan là một bộ truyện tranh trinh thám Nhật Bản của tác giả Aoyama Gõshõ. Nhân vật chính của truyện là một thám tử học sinh trung học có tên là Kudo Shinichi - thám tử học đường xuất sắc - một lần bị bọn tội phạm ép uống thuốc độc và bị teo nhỏ thành học sinh tiểu học lấy tên là Conan Edogawa và luôn cố gắng truy tìm tung tích tổ chức Áo Đen nhằm lấy lại hình dáng cũ.<p>Giá sản phẩm trên Tiki đã bao gồm thuế theo luật hiện hành. Tuy nhiên tuỳ vào từng loại sản phẩm hoặc phương thức, địa chỉ giao hàng mà có thể phát sinh thêm chi phí khác như phí vận chuyển, phụ phí hàng cồng kềnh, ...</p></div>',
1,50,15700,22,20000,0,5,1,'' );
insert into tbl_sanpham(id,nameProduct,imgProduct, describes, status, quantity, discount, percentDiscount, price, view, idDM,idNCC,author)
values(24,'Combo Thám Tử Lừng Danh Conan','0912bc3aad24fd7c0fe6f153e9e1bfe3.jpg','<div>Mở đầu câu truyện, cậu học sinh trung học 17 tuổi Shinichi Kudo bị biến thành cậu bé Conan Edogawa. Shinichi trong phần đầu của Thám tử lừng danh Conan được miêu tả là một thám tử học đường xuất sắc. Trong một lần đi chơi công viên "Miền Nhiệt đới" với cô bạn từ thuở nhỏ Ran Mori, cậu tình cờ chứng kiến vụ một án giết người, Kishida - một hành khách trong trò chơi Chuyến tàu tốc hành đã bị giết một cách dã man. Cậu đã giúp cảnh sát làm sáng tỏ vụ án. Trên đường về nhà, cậu vô tình phát hiện một vụ làm ăn mờ ám của những người đàn ông mặc toàn đồ đen. Khi chúng phát hiện ra cậu, Shinichi đã bị đánh ngất đi. Sau đó những người đàn ông áo đen đó đã cho cậu uống một thứ thuốc độc chưa qua thử nghiệm là Apotoxin-4869 (APTX 4869) với mục đích thủ tiêu cậu. Tuy nhiên chất độc đã không giết chết Kudo. Khi tỉnh lại, cậu bàng hoàng nhận thấy mình đã bị teo nhỏ lại thành hình dạng của một cậu học sinh tiểu học.<br>
<br>Theo lời khuyên của Tiến sĩ Hiroshi Agasa, Shinichi đã che giấu tung tích, để tránh việc Tổ chức Áo đen có thể phát hiện ra rằng cậu vẫn còn sống. Khi Ran hỏi tên cậu, Shinichi đã ghép "Conan" trong tên của Sir Arthur Conan Doyle và "Edogawa" trong tên của Edogawa Rampo, buột miệng nói ra tên mình là "Conan Edogawa". Tiến sĩ Agasa đã nói Conan là một người cháu của mình, nhưng hiện ông đang quá bận rộn không thể chăm sóc cho chú bé nên đã nhờ Ran trông nom Conan giúp mình. Ran nhận lời và từ đó Conan sống tại nhà của Ran tức văn phòng thám tử Mori, vừa che giấu thân phận vừa điều tra tung tích của Tổ chức Áo đen và tìm kiếm thuốc giải độc.<br>
<br>Cha của Ran, Kogoro Mori (Richard Moore) là một thám tử bất tài. Từ khi Conan giúp ông phá án, ông trở nên rất nổi tiếng với biệt danh "Mori ngủ gật". Vì bộ dạng bé nhỏ của Conan, cảnh sát chẳng mấy khi để tâm tới những phán đoán, suy luận của cậu bé. Conan, bằng cách bắn súng gây mê để cho ông Mori ngủ say, sau đó sử dụng thiết bị đổi giọng nói là chiếc nơ gắn trên cổ áo để giả giọng ông, đã giúp cảnh sát phá rất nhiều vụ án dưới danh nghĩa Mori. Cũng có lúc cậu gợi ý và dẫn dắt ông Mori tìm ra chìa khóa của vụ án hay phá án dưới danh nghĩa của Suzuki Sonoko, bạn thân của Ran.<br>
<br>Một số nhân vật quan trọng khác xuất hiện về sau là cha mẹ của Shinichi: Yusaku (Booker) và Yukiko Kudo (Vivian), Heiji Hattori - một thám tử đến từ Osaka, Siêu trộm Kid, nhà sáng chế ra thuốc APTX - 4869 - Sherry ( người của Tổ chức Áo đen, cũng bị biến thành một đứa trẻ sau khi uống chính loại thuốc độc mình đã sáng chế ra với hy vọng chạy trốn khỏi tổ chức), các thành viên của Tổ chức Áo đen: Gin, Vodka, Tequila, Calvados, Pisco, Vermouth, Kir, Chianti, Köln, và một "ông trùm" bí ẩn chỉ được nhắc đến rất mơ hồ.<br>
<br>Để duy trì vỏ bọc bên ngoài, Conan đi học ở trường Tiểu học Teitan và kết bạn với ba đứa trẻ ở trường: Genta Kojima, Mitsuhiko Tsuburaya, và Ayumi Yoshida, lập ra Đội thám tử nhí lớp 1B. Bộ tứ đã có nhiều cuộc phiêu lưu với nhau và ba đứa trẻ đã cho thấy khả năng làm trợ lý thám tử ở tuổi của chúng. Sau này, Haibara - tức Sherry cũng trở thành thành viên của đội thám tử nhí này.<br>
<br>Trải qua nhiều vụ án, Conan khám phá ra rằng FBI và CIA cũng đang truy đuổi Tổ chức Áo đen. Cùng với các thành viên Áo đen đang dần dần lộ mặt, truyện xuất hiện thêm một số điệp viên của FBI và CIA như Shuichi Akai, Jodie Starling, James Black, Mizunashi R<br>
<br>Mời các bạn đón đọc!<p>Giá sản phẩm trên Tiki đã bao gồm thuế theo luật hiện hành. Tuy nhiên tuỳ vào từng loại sản phẩm hoặc phương thức, địa chỉ giao hàng mà có thể phát sinh thêm chi phí khác như phí vận chuyển, phụ phí hàng cồng kềnh, ...</p></div>',
1,50,1842900,3,1900000,0,5,1,'' );
insert into tbl_sanpham(id,nameProduct,imgProduct, describes, status, quantity, discount, percentDiscount, price, view, idDM,idNCC,author)
values(25,'Thám Tử Lừng Danh Conan Tập 91','b6c43feb185df0462f74c018704dba0e.jpg','<div><p>Sự thật nào sẽ được làm sáng tỏ đằng sau mối bất hòa giữa hai con người phục vụ công lí ở hai vị thế khác nhau - mật vụ FBI Akai và cảnh sát Amuro!?</p>
<p>Cuộc phiêu lưu mới sẽ đưa độc giả đến gần hơn với Tổ chức Áo Đen, tiết lộ mối quan hệ giữa Sera và “em gái ngoài lãnh địa”!!</p>
<p>Cuối cùng, chuyện tình cảm giữa Heiji và Kazuha cũng có nhiều chuyển biến…!! Tóm lại là sau một thời gian gây bão, thám tử Conan tập 90 đã ấn định ngày phát hành: 24.02 trên toàn quốc!! Chúc các bạn một năm mới tưng bừng và hào hứng nhé…!!</p><p>Giá sản phẩm trên Tiki đã bao gồm thuế theo luật hiện hành. Tuy nhiên tuỳ vào từng loại sản phẩm hoặc phương thức, địa chỉ giao hàng mà có thể phát sinh thêm chi phí khác như phí vận chuyển, phụ phí hàng cồng kềnh, ...</p></div>',
1,40,20000,0, 20.000, 0,5,1,'' );
insert into tbl_sanpham(id,nameProduct,imgProduct, describes, status, quantity, discount, percentDiscount, price, view, idDM,idNCC,author)
values(26,'Âm Nhạc 1','695c6741792f2b8499781dd8f764c281.jpg','<div><p style="text-align: justify;">Tiếp cận và tham khảo các bộ SGK Âm nhạc của các quốc gia có nền giáo dục tiên tiến như Singapore, Hàn Quốc, Nhật Bản, Hoa Kì…, SGK Âm nhạc 1 phát triển hệ thống chủ đề kết hợp giữa nội dung âm nhạc với văn hoá, xã hội…</p> 
  <p style="text-align: justify;">Sách vận dụng các phương pháp giáo dục âm nhạc tiên tiến như Kodály, Orff-Schulwerk và Dalcroze (Ví dụ: nốt nhạc bàn tay, nốt nhạc hình tượng, âm tiết tấu, nghe nhạc cảm thụ và vận động, chơi nhạc cụ gõ kết hợp với các vận động vỗ tay, búng tay, vỗ chân, giậm chân…).</p> 
  <p style="text-align: justify;">Sách cũng vận dụng các ưu điểm về phương pháp, nội dung của SGK hiện hành (nguồn bài hát, các bài học về tác giả − tác phẩm, âm nhạc và đời sống…).</p> 
  <p style="text-align: justify;">Phát huy tính ưu việt của kênh hình ảnh, nguồn tư liệu đa phương tiện; sử dụng hợp lí kênh chữ, SGK Âm nhạc 1 chú trọng đến các yếu tố thẩm mĩ, phù hợp với lứa tuổi học sinh đầu cấp tiểu học.</p><p>Giá sản phẩm trên Tiki đã bao gồm thuế theo luật hiện hành. Tuy nhiên tuỳ vào từng loại sản phẩm hoặc phương thức, địa chỉ giao hàng mà có thể phát sinh thêm chi phí khác như phí vận chuyển, phụ phí hàng cồng kềnh, ...</p></div>',
1,40,11000,8,12000,0,2,2,'' );
insert into tbl_sanpham(id,nameProduct,imgProduct, describes, status, quantity, discount, percentDiscount, price, view, idDM,idNCC,author)
values(27,'Luyện Tập Mĩ Thuật Lớp 5','30.u4939.d20170703.t100732.837758.jpg','<div><p>Bộ sách<strong> Luyện Tập Mĩ Thuật Lớp 5</strong> gồm 2 tập được biên soạn theo chương trình sách giáo khoa hiện hành nhằm khơi gợi và phát huy khiếu thẩm mỹ của các em. Bên cạnh đó, sách còn là công cụ giúp giáo viên chủ động tổ chức dạy học môn Mỹ Thuật theo chủ đề, phát huy các hình thức hoạt động học tập tích cực, giúp học sinh chủ động, sáng tạo trên tinh thần vừa học vừa chơi, vui học, thích học bộ môn này.<strong> </strong></p>
<p>&nbsp;</p><ul></ul><p>Giá sản phẩm trên Tiki đã bao gồm thuế theo luật hiện hành. Tuy nhiên tuỳ vào từng loại sản phẩm hoặc phương thức, địa chỉ giao hàng mà có thể phát sinh thêm chi phí khác như phí vận chuyển, phụ phí hàng cồng kềnh, ...</p></div>',
1,30,18000,5,19000,0,2,2,'');
insert into tbl_sanpham(id,nameProduct,imgProduct, describes, status, quantity, discount, percentDiscount, price, view, idDM,idNCC,author)
values(28,'Bài Giảng Và Hướng Dẫn Chi Tiết Toán Lớp 4(Tập 2)','img014.u2751.d20170407.t101355.7907.jpg','<div><p><strong>Bài Giảng Và Hướng Dẫn Chi Tiết Toán Lớp 4 - Tập 2</strong></p>
<p>Cuốn sách <strong>Bài Giảng Và Hướng Dẫn Chi Tiết Toán Lớp 4 - Tập 2</strong> - Mô Hình Trường Học Mới VNEN gồm các bài giảng và hướng dẫn giải chi tiết các bài tập toán, mang đến cho các em học sinh lớp 4 một nguồn tài liệu tham khảo hữu ích.</p><p>Giá sản phẩm trên Tiki đã bao gồm thuế theo luật hiện hành. Tuy nhiên tuỳ vào từng loại sản phẩm hoặc phương thức, địa chỉ giao hàng mà có thể phát sinh thêm chi phí khác như phí vận chuyển, phụ phí hàng cồng kềnh, ...</p></div>',
1,30,26000,32,38000,0,2,2,'');
insert into tbl_sanpham(id,nameProduct,imgProduct, describes, status, quantity, discount, percentDiscount, price, view, idDM,idNCC,author)
values(29, 'Sword Art Online 003:Fairy Dance','sao3 cover 1.u335.d20160411.t145256_2.jpg','<div><p style="text-align: justify;"><span style="color: #ff6600; font-size: medium;"><strong>Sword Art Online (Tập 3)</strong></span></p>
<p style="text-align: justify;">Rời trò chơi sinh tử Sword Art Online trở về hiện thực, Kirito lập tức đi tìm những người bạn kề vai sát cánh với mình trong trò chơi ấy. Dĩ nhiên cũng ráo riết kiếm tìm dấu vết người vợ yêu quý Asuna. Nhưng hóa ra Asuna vẫn chưa thoát thân được khỏi trò chơi.</p>
<p style="text-align: justify;">Hoàn toàn không hiểu tình hình này là thế nào, Kirito không khỏi sinh lòng tuyệt vọng. Manh mối duy nhất của cậu là một file ảnh lạ lùng cho thấy Asuna đứng trong một chiếc lồng với hình dạng “tinh linh”. Dường như cô đang bị giam hãm Alfheim Online, một trò chơi VRMMO tính năng cao.</p>
<p style="text-align: justify;">Để giải cứu Asuna, Kirito lao vào thế giới ALO đông đảo tinh linh ấy.</p>
<p style="text-align: justify;">Và câu chuyện Fairy Dance bắt đầu…</p><p>Giá sản phẩm trên Tiki đã bao gồm thuế theo luật hiện hành. Tuy nhiên tuỳ vào từng loại sản phẩm hoặc phương thức, địa chỉ giao hàng mà có thể phát sinh thêm chi phí khác như phí vận chuyển, phụ phí hàng cồng kềnh, ...</p></div>'
,1,50,80000,20,100000,0,4,8,'');
insert into tbl_sanpham(id,nameProduct,imgProduct, describes, status, quantity, discount, percentDiscount, price, view, idDM,idNCC,author)
values(30,'Sherlock Holmes Toàn Tập','a4fececbba40be27dbfd32ca66b0a6f1.jpg','<div><h3>Sherlock Holmes Toàn Tập</h3>
Cái tên Sherlock Holmes đã quen thuộc khắp thế giới tới mức một người dù có thể chưa hề đọc truyện về nhà thám tử này nhưng chỉ cần nghe tên cũng biết anh ta là ai. Sherlock Holmes đã trở thành một biểu tượng của văn hóa đại chúng toàn cầu. Khác với những nhân vật thần tượng chỉ vang bóng một thời, Sherlock Holmes kể từ khi xuất hiện lần đầu tiên năm 1887 qua sáng tạo của Sir Arthur Conan Doyle vẫn sống mãi qua ba thế kỉ.
Sherlock Holmes hiện lên qua lời kể của cộng sự thân thiết và người viết tiểu sử tận tụy - bác sĩ Watson như một chân dung độc đáo, là chuyên gia số một trong lĩnh vực điều tra hình sự và khoa học suy luận, "chiến sĩ bảo vệ công lí lỗi lạc nhất" của thời đại. Trong sự nghiệp truy lùng tội phạm, vị thám tử đại tài từng trải qua nhiều thử thách gay cấn, thậm chí đã một lần chết đi sống lại, nhưng cũng chính nhờ đó, Holmes trở thành một nhân vật bất tử, được độc giả khắp thế giới yêu mến vì tài trí và chất nghệ sĩ, vì cả những nhược điểm lẫn cá tính lập dị.
<br>Bản dịch mới này tiếp cận tác phẩm của Doyle trên&nbsp; cả&nbsp; góc&nbsp; độ&nbsp; lịch&nbsp; sử&nbsp; và&nbsp; văn&nbsp; chương, không xem&nbsp; toàn&nbsp; tập&nbsp; Sherlock Holmes như những truyện trinh thám phổ thông mà là một danh tác kinh điển. Bộ Sherlock Holmes toàn tập 3 tập, bìa mềm, hộp ngang có thêm Phụ bản in màu ở cuối tập 3 về Bảo tàng Sherlock Holmes.
Nội dung từng tập:
Tập 1
Sherlock Holmes lần đầu ra mắt công chúng trong một vụ án mạng hóc hiểm với tựa đề Cuộc điều tra màu đỏ (1887). Đây là khởi điểm của tình bạn lâu bền giữa Sherlock Holmes và bác sĩ Watson mà rồi đây sẽ làm đổi thay lịch sử loại hình tiểu thuyết trinh thám. Tiếp đó, trong Dấu bộ tứ (1890), đôi bạn Holmes và Watson tái xuất trong một vụ án mạng không kém phần li kì, phức tạp. Hai thiên truyện đầu ấy, hiện lên sinh động qua lời kể của bác sĩ Watson, không chỉ giới thiệu với độc giả phương pháp điều tra và suy luận của nhà thám tử tài ba mà còn góp phần định hình phong cách cho những truyện Sherlock Holmes sáng tác sau này.
Tập 2
Tập truyện ngắn thứ hai Những hồi ức về Sherlock Holmes (1894) mở ra cho độc giả cái nhìn toàn diện hơn về một Sherlock Holmes sở hữu nhiều năng lực xuất chúng nhưng cũng vô cùng lập dị. Cũng trong loạt truyện này, độc giả được hé lộ về vụ án đầu tiên đã tạo nên bước ngoặt đưa Holmes vào sự nghiệp thám tử; nhưng đáng nhớ nhất có lẽ là Vụ án cuối cùng, cuộc đối đầu gay cấn giữa Holmes và đối thủ nguy hiểm nhất trong giới tội phạm - giáo sư Moriarty.
Tập 3
Khởi đầu từ một vụ án lắt léo tại vùng quê Anh quốc, Thung lũng Kinh hoàng (1915) đưa độc giả tới một vùng mỏ của Hoa Kì - sân khấu u ám cho những mưu mô, những cuộc đấu đá, thanh trừng, khủng bố của một băng đảng đã gieo rắc nỗi khiếp sợ cho biết bao con người. Cách dẫn dắt truyện ở đây gợi nhớ đến hai đoản thiên tiểu thuyết đầu cũng gắn với những vụ án có căn nguyên sâu xa từ hàng chục năm về trước.<p>Giá sản phẩm trên Tiki đã bao gồm thuế theo luật hiện hành. Tuy nhiên tuỳ vào từng loại sản phẩm hoặc phương thức, địa chỉ giao hàng mà có thể phát sinh thêm chi phí khác như phí vận chuyển, phụ phí hàng cồng kềnh, ...</p></div>',
1,30,562500,25,750000,0,5,6,'');
select *from tbl_sanpham;
insert into tbl_sanpham(id,nameProduct,imgProduct, describes, status, quantity, discount, percentDiscount, price, view, idDM,idNCC,author)
values();

insert into tbl_sanpham(id, nameProduct, describes, status, quantity, discount, price, view, idDM,imgProduct) values (1,'Bí mật cookies',
'<p style="text-align: justify;">“Chúng ta chỉ có một cuộc đời, một cơ hội để làm tất cả những gì mình thích. Hãy suy nghĩ thật - kĩ trước khi làm một điều gì đó, và hãy làm những gì mà bản thân mình thấy vui, đừng bao giờ hối hận về bất cứđiều gì.”</p>
<p style="text-align: justify;">Tôi tự nói với chính mình như thế trước khi đặt bút - cầm máy ảnh lên và viết cuốn sách đầu tay của mình. Đây là cuốn sách mà tôi đã ấp ủ trong suốt hai năm, tính từ cái ngày đầu tiên tôi bắt đầu bước chân vào con đường đầy ngọt ngào tôi đang đi. Tôi không dám tự nhận mình là một kẻ giỏi làm bánh hay đủ nhiều kiến thức về ngành bánh ngọt rộng lớn này. Bạn biết đấy, khi bạn giỏi về một lĩnh vực gì đó, chắc chắn sẽ có một người khác giỏi hơn, và người đó chính là mục tiêu mà bạn cần phải phấn đấu để đạt được. Đơn giản, vì tôi chỉ là một kẻ mê bánh, yêu bánh, “say” bánh và làm bánh vì đam mê."</p>
<p style="text-align: justify;">(Tác giả Minh Đức)</p>
<p style="text-align: center;"><img src="https://vbooks.exdomain.net/image/catalog/products/ready-to-cook-bi-mat-cookies--1-.jpg" /></p>
<p style="text-align: justify;">Cuốn sách do tác giả trẻ Minh Đức - chủ nhân blog Bếp nhà Sói - chuyên về bánh ngọt thực hiện. Theo chia sẻ của chính tác giả: “Chúng ta chỉ có một cuộc đời, một cơ hội để làm tất cả những gì mình thích. Hãy suy nghĩ thật kĩ trước khi làm một điều gì đó, và hãy làm những gì mà bản thân mình thấy vui, đừng bao giờ hối hận về bất cứ điều gì.” Đó có lẽ cũng là lí do mà chàng trai ấy tìm đến và gắn bó với bánh trái trong suốt chặng đường 3 năm.</p>
<p style="text-align: justify;">3 năm để học hỏi, trau dồi, tích luỹ, chàng trai ấy dần dần trở thành một cái tên có chỗ đứng riêng mỗi khi nhắc đến các home-cooks chuyên về mảng bánh ngọt. Đam mê con người đến từ đâu, đó là câu hỏi khó để giải thích, chỉ biết rằng Minh Đức đã được là-chính-mình trong căn bếp nhỏ, nơi cậu có thể đùa vui với với bơ-bột-sữa-trứng-đường, nơi cậu thoả sức sáng tạo và hồi hộp chờ những miếng nhỏ xinh toả hương từ lò nướng.</p>
<p style="text-align: justify;">Bí mật cookies tái hiện lại không gian bếp nhà, với những cảm nhận, ghi chép chân thực của tác giả về những thành bại đã trải qua. Gần 40 công thức đa dạng về các loại cookies hứa hẹn trở thành cẩm nang gối đầu giường cho những ai bắt đầu nảy sinh đam mê với bánh trái.</p>
<p style="text-align: justify;">Hãy cùng chờ đón Bí mật cookies để xem chúng ta sẽ tìm được những thú vị!</p>
<p style="text-align: center;"><img src="https://vbooks.exdomain.net/image/catalog/products/ready-to-cook-bi-mat-cookies--2-.jpg" /></p>
',1,12,97000,129000,1, 1,'readytocookbimatcookies1-255x370.jpg');

insert into tbl_sanpham(id, nameProduct, describes, status, quantity, discount, price, view, idDM,imgProduct) values (6,'LĂN VÀO BẾP',
'<p style="text-align: justify;">Nấu ăn với người này là một góc yêu thương, là thư giãn, là tài năng hay sở thích. Nhưng đối với nhiều người thì nấu ăn là cả một Thử Thách Khó Khăn hay Nỗi Kinh Hoàng Khó Nói. Làm thế nào để công việc nấu ăn trở nên dễ thở hơn với những người không có năng khiếu hay lười biếng, hoặc vừa lười vừa thường gây thảm họa (như cánh họa sĩ chẳng hạn)? Đừng lo, câu hỏi đó không còn là câu hỏi tu từ nữa mà đã có lời giải đáp cho bạn ngay ở đây.</p>
<p style="text-align: justify;">Mọi thứ liên quan đến bếp núc đều có bí quyết riêng để xử lý, nếu bạn nắm được những bí quyết nho nhỏ này thì hãy an tâm là bạn đã thành công một phần rồi đó. Phần còn lại phụ thuộc vào quyết tâm (hay lý do!?) lăn vào bếp của bạn. Dù bạn học nấu ăn vì bị ép buộc, bị cưỡng chế, bị dụ dỗ, hay rảnh quá nên nghía chơi chút, hay bất cứ lý do nào, hãy cùng biến công cuộc vào bếp thành những khám phá thú vị và mới lạ.</p>
<p style="text-align: justify;">Cùng trải nghiệm những mẹo vặt nấu nướng, những công thức nấu ăn đơn giản và những loại thực phẩm cải thiện tính cách có trong Bí kíp nấu ăn: Lăn vào bếp của hai họa sĩ siêu lười, siêu đoảng của Cloud Pillow Studio. Một cuốn sách dễ thương, đầy màu sắc, vui nhộn, thú vị, bổ ích và cần có trên giá sách, bên kệ bếp và trên bàn ăn của bạn.</p>
',1,12,75000,56000,1,1,'bikipnauanlanvaobep1-468x500.jpg');

insert into tbl_sanpham(id, nameProduct, describes, status, quantity, discount, price, view, idDM,imgProduct) values (3,'THAI GIÁO THEO CHUYÊN GIA',
'<p style="text-align: justify;">Thai giáo theo nghĩa rộng chính là thông qua chế độ dinh dưỡng, môi trường và tinh thần để thúc đẩy sự phát triển toàn diện của trẻ. Theo nghĩa hẹp thai giáo là căn cứ vào thời điểm cụ thể để áp dụng các biện pháp như: nghe nhạc, chiếu sáng, tắm nắng, nói chuyện... để giúp bé chào đời khỏe, đẹp, thông minh.</p>
<p style="text-align: justify;">- Hiện nay dòng sách về thai giáo đã quá nhiều rồi, nhưng cuốn sách này lại khiến tôi có cách nhìn nhận mới, không ngờ thai giáo đơn giản mà lại hiệu quả thế.<br />
(Mẹ Tôm)</p>
<p style="text-align: center;"><img src="https://vbooks.exdomain.net/image/catalog/products/thai-giao-theo-chuyen-gia-280-ngay-moi-ngay-doc-mot-trang-kem-dia--1-.jpg" /></p>
<p style="text-align: justify;">- Tôi cho rằng kiến thức thai giáo hầu hết đều "giáo điều" khô cứng, cho tới khi đọc cuốn sách này, có nó trong tay, tôi chỉ cần cùng bé yêu nghe một bản nhạc, cắm một lọ hoa, đi dạo một vòng... thế là hoàn thành bài thai giáo của một ngày. Không vất vả cũng không khó hình dung.<br />(Mẹ bé Bi)</p>
<p style="text-align: justify;">- Nếu nói thai giáo tạo ra kỳ tích, tôi không tin. Cuốn sách này nói với tôi thai giáo không phải lúc nào cũng tạo ra kỳ tích, nhưng chắc chắn thai giáo có thể khiến con tôi khỏe, đẹp, thông minh nhất trong khả năng của cháu. Và tôi đã chọn nó.<br />(Mẹ bé Mèo)</p>
<p style="text-align: center;"><img src="https://vbooks.exdomain.net/image/catalog/products/thai-giao-theo-chuyen-gia-280-ngay-moi-ngay-doc-mot-trang-kem-dia--2-.jpg" /></p>',1,12,69000,98000,1, 3,
'thaigiaotheochuyengia280ngaymo-255x370.jpg');
insert into tbl_sanpham(id, nameProduct, describes, status, quantity, discount, price, view, idDM,imgProduct) values (4,'108 BÍ QUYẾT GIÁO DỤC CON',
'<p style="text-align: justify;">Làm cha mẹ là một sự kiện trọng đại và vui vẻ trong cuộc đời.</p>
<p style="text-align: justify;">Bắt đầu từ khoảnh khắc con trai bạn chào đời, bạn đã có niềm vui vô cùng tận. Cùng với niềm vui ấy, khi làm cha mẹ cũng có nghĩa là bạn đang gánh trên vai trách nhiệm quan trọng nhất của cuộc đời. Bạn phải dạy con nói chuyện, dạy con học đọc, dạy con học cách làm một số việc nhà hợp với sức mình, dạy con học cách chung sống hòa bình với các bạn, dạy con học cách suy nghĩ độc lập… Ngoài ra, bạn còn phải gánh vác trách nhiệm bồi dưỡng phẩm chất và đạo đức cho con, bồi dưỡng con trở thành nam tử hán, có tính cách kiên cường, phẩm chất vượt trội, tự tin, lạc quan…</p>
<p style="text-align: justify;">Là nhà thiết kế đầu tiên trong cuộc đời trẻ, bạn phải cung cấp cho trẻ những phẩm chất cần thiết, và phải bồi dưỡng cho trẻ khả năng giao tiếp, khả năng thích ứng xã hội… So với những kiến thức, kỹ năng mà nhà trường cung cấp cho trẻ, thì những điều này càng có quyết định tới sự thành công của trẻ trong tương lai.</p>
<p style="text-align: center;"><img src="https://vbooks.exdomain.net/image/catalog/products/108-bi-quyet-giao-duc-con-cua-cha-me-thong-thai--1-.jpg" /></p>
<p style="text-align: justify;">Bạn đã chuẩn bị sẵn sàng chưa?</p>
<p style="text-align: justify;">Bạn có biết làm thế nào để rèn luyện ý thức tự lập cho trẻ không?</p>
<p style="text-align: justify;">Bạn có biết làm thế nào để bồi dưỡng khả năng học tập ưu tú cho trẻ không?</p>
<p style="text-align: justify;">Làm thế nào để bồi dưỡng cá tính lành mạnh cho trẻ?</p>
<p style="text-align: justify;">Bạn có biết làm thế nào để nâng cao EQ cho con không?</p>
<p style="text-align: justify;">Bạn có biết làm thế nào để bồi dưỡng thói quen sinh hoạt lành mạnh cho trẻ không?</p>
<p style="text-align: justify;">Có lẽ bạn vẫn chưa hiểu rõ hoặc thiếu lý luận và hướng dẫn thực hiện chi tiết. Hãy bắt đầu từ cuốn sách này để tìm ra những điểm mấu chốt cần phải bồi dưỡng để con trai trở thành người ưu tú.</p>
<p style="text-align: justify;">Bồi dưỡng phẩm chất và thói quen cho trẻ là một quá trình lâu dài, cần sự giáo dục và dẫn dắt không ngừng, hơn nữa còn cần phải bắt đầu từ nhỏ. Bạn càng sớm nắm được phương pháp giáo dục đúng đắn, dựa vào đặc điểm của từng độ tuổi để áp dụng phương thức giáo dục phù hợp thì sự trưởng thành của trẻ cũng sẽ càng thuận lợi.</p>
<p style="text-align: justify;">Kết hợp quan niệm giáo dục trong và ngoài nước để bồi dưỡng 10 khía cạnh quan trọng nhất của trẻ; cung cấp 108 chi tiết quan trọng, đưa ra những phương pháp nổi bật và tính ứng dụng cao, hi vọng, cuốn sách có thể giúp ích cho các bậc phụ huynh, giúp bạn lựa chọn phương thức giáo dục thích hợp hơn cho con trai của mình.</p>
<p style="text-align: center;"><img src="https://vbooks.exdomain.net/image/catalog/products/108-bi-quyet-giao-duc-con-cua-cha-me-thong-thai--2-.jpg" /></p>',
1,12,129000,90000,1,3,'108biquyetgiaoducconcuachameth-255x370.jpg');

